# Generated by Django 5.2.1 on 2025-09-15 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment', '0002_job_created_by_job_requirements_job_responsibility_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidateapplication',
            name='stage',
            field=models.CharField(choices=[('applied', 'Applied'), ('phone screen', 'Phone Screen'), ('interview', 'Interview'), ('rejected', 'Rejected')], default='applied', max_length=20),
        ),
    ]
