# Generated by Django 5.2.1 on 2025-10-25 09:58

import hr_recruitment.storage_backends
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment', '0004_candidate_rename_responsibility_job_benefits_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='resume',
            field=models.FileField(storage=hr_recruitment.storage_backends.PrivateMediaStorage(), upload_to='applicant_cvs/'),
        ),
        migrations.AlterUniqueTogether(
            name='application',
            unique_together={('job', 'candidate')},
        ),
    ]
