# Generated by Django 5.2.1 on 2025-10-29 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment', '0005_alter_candidate_resume_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='experience',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
