# Generated by Django 5.2.1 on 2025-11-01 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recruitment", "0006_candidate_experience"),
    ]

    operations = [
        migrations.AlterField(
            model_name="application",
            name="applied_at",
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name="application",
            name="stage",
            field=models.CharField(
                choices=[
                    ("applied", "Applied"),
                    ("screening", "Screening"),
                    ("interview", "Interview"),
                    ("hired", "Hired"),
                    ("rejected", "Rejected"),
                ],
                db_index=True,
                default="applied",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="candidate",
            name="email",
            field=models.EmailField(db_index=True, max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name="job",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name="job",
            name="is_open",
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AddIndex(
            model_name="application",
            index=models.Index(
                fields=["-applied_at"], name="recruitment_applied_856ada_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="application",
            index=models.Index(
                fields=["stage", "-applied_at"], name="recruitment_stage_745698_idx"
            ),
        ),
    ]
